ARG BUILD_VERSION
FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu

FROM golang:${BUILD_VERSION}-alpine as go

FROM golangci/golangci-lint:latest-alpine as lint

FROM accelbyte/ops-test-alpine:latest-arm64v8
LABEL maintainer "operations@accelbyte.net"
COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin
COPY --from=go /usr/local/go/ /usr/local/go/
COPY --from=lint /usr/bin/golangci-lint /usr/bin/golangci-lint
ENV PATH="/usr/local/go/bin:${PATH}"
ENTRYPOINT ["go"]
