ARG GO_VERSION
FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu

FROM golang:${GO_VERSION} as go

FROM golangci/golangci-lint:latest as lint

FROM accelbyte/debian:latest-arm64v8
LABEL maintainer "operations@accelbyte.net"
COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin
COPY --from=go /usr/local/go/ /usr/local/go/
COPY --from=lint /usr/bin/golangci-lint /usr/bin/golangci-lint
ENV PATH="/usr/local/go/bin:${PATH}"
ENTRYPOINT ["go"]
