ARG GO_VERSION

FROM golang:${GO_VERSION} as go

FROM golangci/golangci-lint:v1.33 as lint

FROM accelbyte/debian:latest
LABEL maintainer "operations@accelbyte.net"
ENV GOPATH="/opt/go"
COPY --from=go /usr/local/go/ /usr/local/go/
COPY --from=lint /usr/bin/golangci-lint /usr/bin/golangci-lint
ENV PATH="/usr/local/go/bin:/opt/go/bin:${PATH}"
ENTRYPOINT ["go"]
