#!/usr/bin/env bash

NODE_VERSION=$(echo ${DOCKER_TAG} | cut -d- -f1)
DOCKERFILE=$(basename -- ${DOCKERFILE_PATH})

docker build . \
  --build-arg NODE_VERSION=${NODE_VERSION} \
  -t ${IMAGE_NAME} \
  -f ${DOCKERFILE}
