# Copyright (c) 2020 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

# Dockerfile for building rust executable with windows target

FROM rust:1.40.0-slim-stretch as builder
RUN apt-get update -y && \
  apt-get install gcc mingw-w64 -y && \
  rustup target add i686-pc-windows-gnu && \
  rustup target add x86_64-pc-windows-gnu
