ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine as node

FROM accelbyte/alpine:latest
LABEL maintainer "operations@accelbyte.net"
RUN apk add --no-cache libstdc++
COPY --from=node /opt /opt
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/bin /usr/local/bin

ENTRYPOINT ["docker-entrypoint.sh"]
