#!/usr/bin/env bash

BUILD_VERSION=$(echo ${DOCKER_TAG} | cut -d "-" -f1)

if [[ ${DOCKER_TAG} == "latest" ]]; then
  docker build . --build-arg BUILD_VERSION=${DOCKER_TAG} -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH}
else
  docker build . --build-arg BUILD_VERSION=${BUILD_VERSION} -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH}
fi
