#!/usr/bin/env bash

BUILD_VERSION=$(echo ${DOCKER_TAG} | cut -d "-" -f1)
BUILD_ARCH=$(echo ${DOCKER_TAG} | cut -d "-" -f2)

if [[ ${BUILD_ARCH} != "amd64" ]]; then
  docker run --rm --privileged multiarch/qemu-user-static:register --reset
fi
